version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: bossaboss-mongodb
    restart: unless-stopped
    ports:
      - "3001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
