version: "3.8"

services:
  redis:
    image: "redis/redis-stack"
    container_name: bossaboss-redis
    ports:
      - "6379:6379"
      - "8001:8001"
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: bossaboss-mongodb
    restart: unless-stopped
    ports:
      - "3001:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
